import type { Product, Kpi } from "@/types";

const U = (id: string, name: string, role: string, color: string) => ({
  id,
  name,
  role,
  initials: name
    .split(" ")
    .map((w) => w[0])
    .join("")
    .slice(0, 2),
  color,
});
export const users = {
  maria: U("maria", "Maria Santos", "NTG Manager", "#7C3AED"),
  rodney: U("rodney", "Rodney Rodriguez", "Territory Lead", "#0EA5E9"),
  karen: U("karen", "Karen Li", "Business Analyst", "#F59E0B"),
  arjay: U("arjay", "Arjay Reyes", "Data Steward", "#10B981"),
  liza: U("liza", "Liza Ramirez", "NTG Analyst", "#EF4444"),
  michael: U("michael", "Michael Tan", "Network Engineer", "#6366F1"),
  john: U("john", "John Dela Cruz", "KPI Owner", "#EC4899"),
};
const teams = {
  cwn: "CWN Analytics Team",
  terr: "Territory Analytics Team",
  ntg: "NTG Insights Team",
  nps: "Customer Experience Team",
  dp: "Data Products Team",
};

const launchFor = (
  family: string,
): { launchType: Product["launchType"]; launchUrl: string } => {
  if (family.startsWith("Eagle Eye"))
    return {
      launchType: "eagle_eye",
      launchUrl: "https://eagle-eye.nai.example/d/",
    };
  if (family.startsWith("NPS"))
    return {
      launchType: "looker",
      launchUrl: "https://looker.nai.example/dashboards/",
    };
  return {
    launchType: "external_url",
    launchUrl: "https://analytics.nai.example/",
  };
};

const baseProducts: Array<Omit<Product, "launchType" | "launchUrl">> = [
  {
    id: "ookla-dash",
    type: "dashboard",
    name: "Ookla Consistency Score Dashboard",
    family: "Eagle Eye — CWN",
    domain: "Network Quality",
    territory: "National",
    segment: "Consumer",
    owner: teams.cwn,
    ownerUser: users.arjay,
    steward: users.michael,
    rating: 4.8,
    reviews: 26,
    certified: true,
    trust: "Trusted",
    accessState: "none",
    icon: "gauge",
    accent: "#7C3AED",
    desc: "Measures consistency of wireless network experience based on Ookla speed test results across time and locations.",
    purpose:
      "Provides visibility into network consistency performance using Ookla data. Helps identify areas with inconsistent user experience and supports improvement initiatives.",
    kpis: ["ookla-consistency", "mobile-availability", "dl-throughput"],
    tags: ["Ookla", "Consistency", "CWN", "Quality"],
    updated: "May 15, 2025",
    refresh: "Daily",
    features: [
      "Consistency score trends",
      "Geographic breakdown",
      "Technology and band analysis",
      "Time-based comparisons",
    ],
  },
  {
    id: "territory-perf",
    type: "dashboard",
    name: "Territory Performance Overview",
    family: "Eagle Eye — Territory",
    domain: "Territory Operations",
    territory: "All Territories",
    segment: "Consumer",
    owner: teams.terr,
    ownerUser: users.rodney,
    steward: users.liza,
    rating: 4.6,
    reviews: 18,
    certified: true,
    trust: "Trusted",
    accessState: "none",
    icon: "map-pin",
    accent: "#4F46E5",
    desc: "Track territory performance, KPIs and operational excellence across regions and cell sites.",
    purpose:
      "A single pane of glass for territory leads to monitor performance, compare regions and prioritise field actions.",
    kpis: ["nps-score", "mobile-availability", "accessibility"],
    tags: ["Territory", "Performance", "Operations"],
    updated: "May 18, 2025",
    refresh: "Daily",
    features: [
      "Regional comparison",
      "Site-level drilldown",
      "Trend tracking",
      "Action prioritisation",
    ],
  },
  {
    id: "ntg-mancom",
    type: "dashboard",
    name: "NTG Mancom Dashboard",
    family: "Eagle Eye — Mancom",
    domain: "Executive",
    territory: "National",
    segment: "VIP",
    owner: teams.ntg,
    ownerUser: users.maria,
    steward: users.john,
    rating: 4.7,
    reviews: 21,
    certified: true,
    trust: "Trusted",
    accessState: "none",
    icon: "layout-grid",
    accent: "#0EA5E9",
    desc: "Executive dashboards for the NTG Management Committee covering top-line network and experience KPIs.",
    purpose:
      "Curated executive view aligning network performance to business outcomes for committee decision-making.",
    kpis: ["nps-score", "ookla-consistency", "churn-risk"],
    tags: ["Executive", "Mancom", "NTG"],
    updated: "May 20, 2025",
    refresh: "Weekly",
    features: [
      "Executive KPI summary",
      "Quarter-over-quarter view",
      "Strategic scorecards",
      "Board-ready exports",
    ],
  },
  {
    id: "nps-insights",
    type: "dashboard",
    name: "NPS Insights",
    family: "NPS Insights",
    domain: "Customer Experience",
    territory: "National",
    segment: "Consumer",
    owner: teams.nps,
    ownerUser: users.karen,
    steward: users.arjay,
    rating: 4.5,
    reviews: 31,
    certified: true,
    trust: "Trusted",
    accessState: "none",
    icon: "smile",
    accent: "#10B981",
    desc: "Customer satisfaction and experience insights across the customer journey and key touchpoints.",
    purpose:
      "Understand customer sentiment, drivers of satisfaction and detractor themes to guide experience improvements.",
    kpis: ["nps-score", "churn-risk", "accessibility"],
    tags: ["NPS", "Customer Experience", "Satisfaction"],
    updated: "May 12, 2025",
    refresh: "Weekly",
    features: [
      "NPS trends",
      "Driver analysis",
      "Verbatim themes",
      "Segment comparison",
    ],
  },
  {
    id: "gtap",
    type: "dataproduct",
    name: "GTAP — Geo Traffic Analytics Platform",
    family: "Data Products",
    domain: "Network Quality",
    territory: "National",
    segment: "B2B",
    owner: teams.dp,
    ownerUser: users.arjay,
    steward: users.michael,
    rating: 4.4,
    reviews: 12,
    certified: true,
    trust: "Trusted",
    accessState: "none",
    icon: "database",
    accent: "#F59E0B",
    desc: "Standardised geo-tagged traffic and experience dataset powering reporting and downstream analytics.",
    purpose:
      "Reusable, governed data product for analysts building bespoke geo-level reporting and models.",
    kpis: ["dl-throughput", "ookla-consistency", "mobile-availability"],
    tags: ["Data Product", "Geo", "Traffic"],
    updated: "May 09, 2025",
    refresh: "Daily",
    features: [
      "Geo-tagged metrics",
      "Governed schema",
      "API + extract access",
      "Lineage tracking",
    ],
  },
  {
    id: "network-quality",
    type: "dashboard",
    name: "Network Quality Overview Dashboard",
    family: "Eagle Eye — CWN",
    domain: "Network Quality",
    territory: "National",
    segment: "Consumer",
    owner: teams.cwn,
    ownerUser: users.michael,
    steward: users.arjay,
    rating: 4.7,
    reviews: 22,
    certified: true,
    trust: "Trusted",
    accessState: "none",
    icon: "activity",
    accent: "#6366F1",
    desc: "Holistic view of network quality across key performance indicators and technologies.",
    purpose:
      "Single entry point to overall network health with drilldown into the metrics that matter most.",
    kpis: ["ookla-consistency", "dl-throughput", "mobile-availability"],
    tags: ["Quality", "CWN", "Overview"],
    updated: "May 16, 2025",
    refresh: "Daily",
    features: [
      "Composite quality index",
      "Technology split",
      "Hotspot detection",
      "Custom thresholds",
    ],
  },
  {
    id: "cwn-capacity",
    type: "report",
    name: "CWN Capacity Report",
    family: "Eagle Eye — CWN",
    domain: "Capacity",
    territory: "National",
    segment: "B2B",
    owner: teams.cwn,
    ownerUser: users.michael,
    steward: users.arjay,
    rating: 4.3,
    reviews: 9,
    certified: false,
    trust: "In Review",
    accessState: "none",
    icon: "bar-chart-3",
    accent: "#0EA5E9",
    desc: "Periodic capacity utilisation report highlighting congestion risk across the radio network.",
    purpose:
      "Supports capacity planning by surfacing utilisation trends and at-risk cells.",
    kpis: ["dl-throughput", "mobile-availability"],
    tags: ["Capacity", "CWN", "Report"],
    updated: "May 10, 2025",
    refresh: "Monthly",
    features: [
      "Utilisation heatmap",
      "Congestion risk",
      "Capacity forecast",
      "Site rankings",
    ],
  },
  {
    id: "so-experience",
    type: "dashboard",
    name: "SO Experience Dashboard",
    family: "NPS Insights",
    domain: "Customer Experience",
    territory: "National",
    segment: "Consumer",
    owner: teams.nps,
    ownerUser: users.karen,
    steward: users.liza,
    rating: 4.6,
    reviews: 14,
    certified: true,
    trust: "Trusted",
    accessState: "none",
    icon: "smile",
    accent: "#EC4899",
    desc: "Service order experience analytics covering activation, provisioning and early-life journeys.",
    purpose:
      "New in the CWN analytics suite — track service order experience end to end.",
    kpis: ["nps-score", "accessibility", "churn-risk"],
    tags: ["NPS", "Service Order", "New"],
    updated: "May 20, 2025",
    refresh: "Daily",
    features: [
      "Journey funnel",
      "Activation SLAs",
      "Experience scoring",
      "Detractor alerts",
    ],
  },
];

/** accessState here is a placeholder — the real value is derived per-user in data-access. */
export const products: Product[] = baseProducts.map((p) => ({
  ...p,
  ...launchFor(p.family),
}));

export const kpis: Kpi[] = [
  {
    id: "ookla-consistency",
    name: "Ookla Consistency Score",
    short: "Consistency Score",
    family: "Eagle Eye — CWN",
    domain: "Network Quality",
    owner: teams.cwn,
    ownerUser: users.arjay,
    rating: 4.6,
    reviews: 14,
    trust: "Trusted",
    dq: 92,
    value: "87.4%",
    trend: "+3.2%",
    trendDir: "up",
    accent: "#7C3AED",
    tags: ["Ookla", "Consistency", "Quality", "KPI"],
    category: "Network Performance",
    upstream: ["Ookla Speedtest Feed", "GTAP — Geo Traffic Analytics Platform"],
    desc: "Percentage of tests that meet consistency thresholds for download and upload speeds.",
    definition:
      "Percentage of Ookla speed tests that meet the defined consistency criteria for both download and upload speeds within a given time window and location.",
    formula: "(Number of consistent tests / Total valid tests) × 100",
    context:
      "High consistency scores indicate stable network performance and predictable user experience.",
    source: "Ookla Speedtest",
    frequency: "Daily",
    aggregation: "Cell Site / Region / Territory",
    thresholds: [
      ["Green", "≥ 85%", "#10B981"],
      ["Amber", "70% – 85%", "#F59E0B"],
      ["Red", "< 70%", "#EF4444"],
    ],
    relatedProducts: ["ookla-dash", "network-quality", "gtap"],
  },
  {
    id: "nps-score",
    name: "Net Promoter Score",
    short: "NPS",
    family: "NPS Insights",
    domain: "Customer Experience",
    owner: teams.nps,
    ownerUser: users.karen,
    rating: 4.7,
    reviews: 19,
    trust: "Trusted",
    dq: 95,
    value: "+42",
    trend: "+5 pts",
    trendDir: "up",
    accent: "#10B981",
    tags: ["NPS", "Experience", "KPI"],
    category: "Customer Experience",
    upstream: ["Experience Survey Platform", "CRM Customer Master"],
    desc: "Likelihood of customers to recommend, measured via survey across the customer base.",
    definition:
      "Percentage of promoters (9–10) minus percentage of detractors (0–6) from relationship and transactional surveys.",
    formula: "% Promoters − % Detractors",
    context:
      "A rising NPS signals improving customer sentiment and lower churn risk.",
    source: "Experience Survey Platform",
    frequency: "Weekly",
    aggregation: "Segment / Region / Journey",
    thresholds: [
      ["Green", "≥ +40", "#10B981"],
      ["Amber", "+20 – +40", "#F59E0B"],
      ["Red", "< +20", "#EF4444"],
    ],
    relatedProducts: ["nps-insights", "so-experience", "ntg-mancom"],
  },
  {
    id: "mobile-availability",
    name: "Mobile Network Availability",
    short: "Availability",
    family: "Eagle Eye — CWN",
    domain: "Network Quality",
    owner: teams.cwn,
    ownerUser: users.michael,
    rating: 4.5,
    reviews: 11,
    trust: "Trusted",
    dq: 90,
    value: "99.2%",
    trend: "+0.3%",
    trendDir: "up",
    accent: "#4F46E5",
    tags: ["Availability", "CWN", "KPI"],
    category: "Network Reliability",
    upstream: ["Network OSS", "GTAP — Geo Traffic Analytics Platform"],
    desc: "Share of time the mobile network is available to serve customers across monitored sites.",
    definition:
      "Proportion of measured time intervals where the network meets the availability threshold across active cell sites.",
    formula: "(Available time / Total monitored time) × 100",
    context:
      "Availability is a foundational reliability metric underpinning customer experience.",
    source: "Network OSS",
    frequency: "Daily",
    aggregation: "Cell Site / Region",
    thresholds: [
      ["Green", "≥ 99%", "#10B981"],
      ["Amber", "97% – 99%", "#F59E0B"],
      ["Red", "< 97%", "#EF4444"],
    ],
    relatedProducts: ["network-quality", "territory-perf", "gtap"],
  },
  {
    id: "dl-throughput",
    name: "Download Throughput",
    short: "DL Throughput",
    family: "Eagle Eye — CWN",
    domain: "Network Quality",
    owner: teams.cwn,
    ownerUser: users.arjay,
    rating: 4.4,
    reviews: 8,
    trust: "Trusted",
    dq: 88,
    value: "64.5 Mbps",
    trend: "+2.1 Mbps",
    trendDir: "up",
    accent: "#0EA5E9",
    tags: ["Throughput", "Speed", "KPI"],
    category: "Network Performance",
    upstream: ["Network Probes", "GTAP — Geo Traffic Analytics Platform"],
    desc: "Median download speed experienced by customers across the radio access network.",
    definition:
      "Median measured download throughput across valid sessions within the reporting period and geography.",
    formula: "Median(session download speeds)",
    context:
      "Throughput reflects perceived speed and is a key driver of satisfaction.",
    source: "Network Probes",
    frequency: "Daily",
    aggregation: "Cell Site / Region / Territory",
    thresholds: [
      ["Green", "≥ 60 Mbps", "#10B981"],
      ["Amber", "40 – 60 Mbps", "#F59E0B"],
      ["Red", "< 40 Mbps", "#EF4444"],
    ],
    relatedProducts: ["network-quality", "cwn-capacity", "gtap"],
  },
  {
    id: "accessibility",
    name: "Accessibility Score",
    short: "Accessibility",
    family: "Eagle Eye — Territory",
    domain: "Network Quality",
    owner: teams.terr,
    ownerUser: users.rodney,
    rating: 4.3,
    reviews: 7,
    trust: "Trusted",
    dq: 86,
    value: "98.6%",
    trend: "-0.2%",
    trendDir: "down",
    accent: "#F59E0B",
    tags: ["Accessibility", "Territory", "KPI"],
    category: "Network Reliability",
    upstream: ["Network OSS"],
    desc: "Success rate of customers accessing the network on first attempt.",
    definition:
      "Percentage of connection setup attempts that succeed within the defined accessibility criteria.",
    formula: "(Successful setups / Total setup attempts) × 100",
    context:
      "Declining accessibility can indicate congestion or coverage gaps requiring field action.",
    source: "Network OSS",
    frequency: "Daily",
    aggregation: "Cell Site / Region / Territory",
    thresholds: [
      ["Green", "≥ 98%", "#10B981"],
      ["Amber", "95% – 98%", "#F59E0B"],
      ["Red", "< 95%", "#EF4444"],
    ],
    relatedProducts: ["territory-perf", "nps-insights", "so-experience"],
  },
  {
    id: "churn-risk",
    name: "Churn Risk Index",
    short: "Churn Risk",
    family: "NPS Insights",
    domain: "Customer Experience",
    owner: teams.nps,
    ownerUser: users.karen,
    rating: 4.2,
    reviews: 6,
    trust: "In Review",
    dq: 79,
    value: "12.4%",
    trend: "-1.1%",
    trendDir: "up",
    accent: "#EF4444",
    tags: ["Churn", "Risk", "KPI"],
    category: "Customer Retention",
    upstream: ["Churn Model v3", "Experience Survey Platform"],
    desc: "Modelled likelihood of customer churn based on experience and network signals.",
    definition:
      "Composite index combining experience, network quality and tenure features into a churn propensity score.",
    formula: "Model(experience, quality, tenure, complaints)",
    context:
      "A falling churn risk index suggests retention efforts and experience gains are working.",
    source: "Churn Model v3",
    frequency: "Weekly",
    aggregation: "Segment / Region",
    thresholds: [
      ["Green", "< 10%", "#10B981"],
      ["Amber", "10% – 15%", "#F59E0B"],
      ["Red", "> 15%", "#EF4444"],
    ],
    relatedProducts: ["nps-insights", "ntg-mancom", "so-experience"],
  },
];

export const currentUser = users.maria;
